### ISSUE TITLE
https://raw.githubusercontent.com/MicrosoftLearning/SC-100-Microsoft-Cybersecurity-Architect/master/Instructions/Labs/LAB_SC_100_Lab3_Ex4_Sensitivity_labels.md

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/SC-100-Microsoft-Cybersecurity-Architect#18]
# Module: 0?
## Lab/Demo: 03
Exercise 4
Part 2
#### Step: 06

Description of issue

Lack of a space between the 1. and the rest of the text in this step breaks numbering:

![image](https://github.com/user-attachments/assets/2ff1ec69-b7b7-426d-ae2b-2a1ac0b005b2)

Recommend adding a space here to match the other steps:

![image](https://github.com/user-attachments/assets/bddee9f8-3d3b-42b6-9a52-f7edb0622409)

**Comment by hrasheed-msft** [comment]
Fixed in new PR
