### ISSUE TITLE
https://raw.githubusercontent.com/MicrosoftLearning/SC-100-Microsoft-Cybersecurity-Architect/master/Instructions/Labs/LAB_SC_100_Lab4_Ex2_Global_Secure_Access.md

### ISSUE THREAD

**Issue by Skillable-MelieKrichko** [MicrosoftLearning/SC-100-Microsoft-Cybersecurity-Architect#19]
# Module: 0?
#### Step: 2

Description of issue:

Bullet points are not aligning and the 'SMB to ContosoFS' on the 'Name' bullet points needs to be type texted.

<img width="214" alt="2024-08-05_155032" src="https://github.com/user-attachments/assets/aa90e243-8b77-4a62-9382-c91149940b4f">

**Comment by hrasheed-msft** [comment]
Fixed in new PR
